### Урок 6. Взаимосвязь величин. Параметрические и непараметрические показатели корреляции. Корреляционный анализ.

In [2]:
import numpy as np

1) Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [69]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
cov = np.mean(zp*ks) - np.mean(zp)*np.mean(ks)
cov # смещенное

9157.839999999997

In [70]:
np.cov(zp, ks, ddof=0) # смещенное

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [71]:
np.cov(zp, ks, ddof=1) # несмещенное

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [72]:
coef_nesm = np.cov(zp, ks, ddof=1)/(np.std(zp, ddof=1)*np.std(ks, ddof=1))
coef_nesm # 0.88749009

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

In [73]:
coef_sm = np.cov(zp, ks, ddof=0)/(np.std(zp, ddof=0)*np.std(ks, ddof=0))
coef_sm # 0.88749009

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

In [74]:
np.corrcoef(zp, ks) # 0.88749009

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

Использовала смещенные показатели ковариации и среднеквадратичных отклонений двух признаков, а потом несмещенные. Коэффициент корреляции получился одинаковый.

2) Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [75]:
iq = [131, 125, 115, 122, 131, 115, 107, 99, 125, 111]
a = 0.05

Используем критерий Стьюдента. Находим среднее квадратичное отклонение по формуле: S = (sum((x(i) - x(ср))2)/(n-1))1/2

In [76]:
iq_av = np.mean(iq)
iq_av

118.1

In [77]:
sum_iq = 0
for i in iq:
    sum_iq += (i - iq_av) ** 2
S = np.sqrt(sum_iq/(len(iq)-1))
S

10.54566788359614

In [78]:
np.std(iq, ddof=1) # проверка

10.54566788359614

In [79]:
len(iq)

10

In [80]:
st = 2.262 # при критерии свободы = 9 = (len(x) - 1) и a = 0.025

In [81]:
left_border = iq_av - st*S/np.sqrt(len(iq))
right_border = iq_av + st*S/np.sqrt(len(iq))
print(f'Доверительный интервал для математического ожидания с надежностью 0.95 {[left_border, right_border]}')

Доверительный интервал для математического ожидания с надежностью 0.95 [110.55660776308164, 125.64339223691834]


3) Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.

left_border = X - z(a/2) * S/(n **1/2)

right_border = X + z(a/2) * S/(n **1/2)

In [82]:
X = M = 174.2
n = 27
D = 25
S = np.sqrt(D)
a = 0.05
z = 1.96 

In [83]:
left_border = X - z*S/np.sqrt(n)
right_border = X + z*S/np.sqrt(n)
print(f'Доверительный интервал для математического ожидания с надежностью 0.95 {[left_border, right_border]}')

Доверительный интервал для математического ожидания с надежностью 0.95 [172.31398912064722, 176.08601087935276]
